# Generated by Django 4.0.6 on 2023-09-18 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_path', models.FileField(upload_to='images/')),
                ('image_embedding', models.BinaryField()),
            ],
        ),
    ]
