# Generated by Django 4.0.6 on 2023-09-18 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_imageembedding_image_embedding_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageembedding',
            name='image_path',
            field=models.FileField(upload_to='images/'),
        ),
    ]
