# Generated by Django 4.0.6 on 2023-09-18 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_imageembedding_image_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageembedding',
            name='image_embedding',
            field=models.TextField(),
        ),
    ]
