# Generated by Django 4.0.6 on 2023-09-18 11:39

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_imageembedding_image_embedding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageembedding',
            name='image_embedding',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None),
        ),
    ]
