# Generated by Django 4.0.6 on 2023-09-20 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_imageembedding_image_embedding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageembedding',
            name='image_embedding',
            field=models.TextField(),
        ),
    ]
