# Generated by Django 4.0.6 on 2023-09-23 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_imageembedding_image_embedding'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageEmbedding',
        ),
    ]
